// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;


    [RequiresSkill(typeof(IndustrySkill), 4)]
    public partial class GrapheneRecipe : RecipeFamily
    {
        public GrapheneRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                "Graphene",  //noloc
                Localizer.DoStr("Graphene"),
                new List<IngredientElement>
                {
					new IngredientElement(typeof(SugarItem), 2),
                },
                new List<CraftingElement>
                {
                    new CraftingElement<GrapheneItem>(1),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 10;
            this.LaborInCalories = CreateLaborInCaloriesValue(150, typeof(IndustrySkill));
            this.CraftMinutes = CreateCraftTimeValue(5);
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Graphene"), typeof(GrapheneRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(ElectricMachinistTableObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Graphene")]
    [Weight(100)]
    [Ecopedia("Items", "Products", createAsSubPage: true)]
    public partial class GrapheneItem : Item
    {
        public override LocString DisplayDescription { get { return Localizer.DoStr(""); } }
        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Graphene"); } }
    }

}